### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by raymoo** [sofar/entity_ai#2]
- Licensing just the artwork under CC-BY-ND does not disallow derivatives on the code, which isn't distributed under the same license. Only issue is that documentation would have to be rewritten from scratch if the API of a fork was different from the original. However, the licenses are still effective in reducing forking, by limiting the number of people who want to work on the project.
- Even if the licenses worked in the way you described, it would make it a little bit harder to contribute since people could not put their changes in a public repository to make a pull request.
- It's not clear if documentation is meant to include code comments
- Forking this mod would have no significant negative consequences, as long as the forks used a different mod name. It would be even beneficial if they provided modified APIs, since modders would have greater choice in how they make their mobs.
- Mobs would not have to switch to a LGPL-compatible license later on, because of the dynamic linking exception.

Though it looks like the repository might be meant more as just an in-progress preview of something you want to merge into minetest_game instead of a standalone mod, since the CC-BY-ND license would prevent it from getting in the mod releases forum. In that case, most of my non-technical criticisms would not apply.

**Comment by sofar** [comment]
The sole purpose of this project is to be merged in minetest_game, hence (1) the restrictive licensing to discourage people from forking and making their own MOB api, or worse, reusing it in other existing mob api's. (2) the CLA, which states that all content will be licensed much more freely if this code manages to make it into minetest_game.

As I'm the current author of all the code and the 3d models, I have asserted my right to put these restrictions on the project. I also do not have any reasons to prevent people from making PRs through github (and I expressly allow it, even though I think it's allowed implicitly).

Obviously it's not in the project's best interest to send out DMCA claims to people who make forks for the purpose of making a PR. I don't mind forks for personal use, even (the licenses allow it, explicitly). But if I find that my 3D models are put into a different mob API, then I have issues with that, since that's a "remix".

So, relax, the goal is to make this thing into minetest_game's monster API of choice. Nobody who genuinely tries to help the project will get into trouble.

**Comment by sofar** [comment]
> It's not clear if documentation is meant to include code comments

never.
